### ISSUE TITLE
Port Trello roadmap to GitHub projects

### ISSUE THREAD

**Issue by csytan** [csytan/cozycal-roadmap#3]
Goal: closer alignment between Kat and Chris

- [x] Make GitHub account for Kat
- [x] Add Kat as a collaborator
- [x] Port doing
- [x] Port incoming
- [x] Add redirect at https://cozycal.com/roadmap

- [x] Update links to roadmap in MailChimp
- [x] Update links to roadmap in our blog
- [x] Update link to roadmap in About page
- [x] Link to new roadmap in Trello
